### ISSUE TITLE
Gmail deleted mails still show in Inbox

### ISSUE THREAD

**Issue by wards999** [bkaankose/Wino-Mail#64] opened 2023-12-02 16:21 UTC
I delete a mail from my Inbox -  it is visually removed.
I then move to the Trash folder and can see the deleted mail.
I then move back to the Inbox and the deleted mail is again visible.

Am I doing something wrong or is this an issue?

**Comment by wards999** [comment] 2023-12-02 20:15
This is just a standard gmail account (not IMAP)

The deleted mail does go into the Trash folder - I can confirm this in Wino-Mail and looking at the standard gmail website. However, when I go back to the Inbox folder in Wino it is still showing up (It has definitely moved as I can again verify in the gmail website)

This problem even persists if I close and re-start Wino Mail (ie the deleted mails are still visible in the Inbox)

Perhaps I should remove and re-add the account?

**Comment by rpierrot** [comment] 2023-12-04 02:14
Same issue here. Looking forward to the hotfix. Thanks.

**Comment by wards999** [comment] 2023-12-07 11:36
Looking good here - thanks for fixing the issue

**Comment by wards999** [comment] 2023-12-07 12:54
This now works if I delete messages in Wino
However, deleted mails via the web client are not reflected in Wino

(Also, Wino Viewed messages are also not being marked as read now - I can raise a new ticket if you prefer)

**Comment by bkaankose** [comment] 2023-12-07 13:52
> Update- Deleted mails via the web client are not reflected in Wino
> 
> (Also, Wino Viewed messages are also not being marked as read now - I can raise a new ticket if you prefer)

I can't reproduce this with Gmail API sync. You need to click synchronization button to receive changes. Can you explain a little bit more about the steps?

**Comment by wards999** [comment] 2023-12-07 15:28
Mails weren't being changed to Read at all - I had to delete and re-add my Gmail account - now they work correctly.

(I also notice that one mail has a different time stamp to the web gmail - there it show 15:00 whereas in Wino shows 09:42 - not sure why this would be the case?)

When I re-added the gmail account into Wino I got the normal gmail security mail to say that wino was accessing my account, I deleted it from the webmail page but it is still showing inside Wino - pressing the sync button isn't changing it

**Comment by wards999** [comment] 2023-12-08 19:00
Further to the previous comment, it appears to only be the gmail security alert message is misbehaving - i deleted this in the web client and it is definitely in the trash folder, but it still shows in the wino inbox. All other mains I delete in the web client do disappear from the wino inbox view when i click the Sync button

**Comment by bkaankose** [comment] 2024-06-14 17:43
Version 1.7.2 is released today. Could you please re-test this with the latest version and validate the fix? I can't reproduce this issue anymore.

**Comment by bkaankose** [comment] 2024-09-10 07:37
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.

**Closed by bkaankose** 2024-09-10 07:37 UTC
Labels: bug, synchronization, fixed
