### ISSUE TITLE
Cannot connect to Proton Mail Bridge

### ISSUE THREAD

**Issue by rafirafirafi** [bkaankose/Wino-Mail#99] opened 2024-01-17 00:45 UTC
It doesn't seems like Wino Mail is able to connect to proton bridge (protonmail uses an IMAP bridge with SSL)
While adding the account, Wino says the server doesnt respond.
Turning on the logs doesn;t give any info

Thanks

**Comment by kareigu** [comment] 2024-03-26 14:02
Having the same issue, nothing showing up in either of the logs as well.

Error:
![image](https://github.com/bkaankose/Wino-Mail/assets/31644842/7591f538-4817-426f-b865-59d94f0d3101)
Proton Bridge settings:
![image](https://github.com/bkaankose/Wino-Mail/assets/31644842/2f68d0c9-03e4-4a72-a469-2fe14aa1fdec)
![image](https://github.com/bkaankose/Wino-Mail/assets/31644842/f800748e-7bf4-459f-b946-df44738b616d)

**Comment by bkaankose** [comment] 2024-04-12 23:39
I think @Benjin had a fix for this issue. It was caused by some certification issue and he stepped in for help.

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/db51c8fa-50f1-440c-b2f1-786f40c03b66)

@rafirafirafi @kareigu could you please try this solution to see if it works for you?

**Comment by Benjin** [comment] 2024-04-12 23:50
Worth noting that it worked for me after I tried that on the beta preview; it’s possible that I also needed some of the fixes between the latest public and the preview.

—
Benjin Dubishar
________________________________

**Comment by kareigu** [comment] 2024-04-13 08:19
I tried exporting the certs from Proton Bridge and adding them as personal keys in certmgr, but didn't change anything.

I'm not understanding how to go about setting the auth to "none". Can't seem to find any setting for this in Proton Bridge nor Wino.

**Comment by Benjin** [comment] 2024-04-13 17:59
@kareigu try with the beta in [this release](https://github.com/bkaankose/Wino-Mail/releases/tag/beta); that's where I was able to get ProtonMail to work.

You'll have to enable Developer Mode and install the app dev certificate on your system for it to install.

**Comment by kareigu** [comment] 2024-04-13 18:28
Aight, with the beta release I can get a bit further where it seemingly connects to Proton Bridge but then fails during "Preparing folders"
![image](https://github.com/bkaankose/Wino-Mail/assets/31644842/cb1e1491-18dd-43ab-9624-9adc564e7a2b)
Nothing in the logs this time either.
Tried setting auth to none as well but no luck.

**Comment by Benjin** [comment] 2024-04-15 03:24
@kareigu Did you set both IMAP and SMTP to "none" auth?  They're two different tabs in the configuration view.

**Comment by kareigu** [comment] 2024-04-15 06:48
Yes

**Comment by Benjin** [comment] 2024-04-22 16:06
I'm out of ideas now.  If you're comfortable building it yourself, can you stick a breakpoint [here](https://github.com/bkaankose/Wino-Mail/blob/75863faf582f77c6d9383683c56b30fb1ad84b5f/Wino.Core/Integration/ImapClientPool.cs#L78) and see what the full error message/stacktrace is?

**Comment by kareigu** [comment] 2024-04-22 19:48
Okay, from building and running I managed to get to the same error message about TLS you had in your Discord message.

However, setting the "Connection security" to None seems to make it able to connect normally.
On 1.6 and beta 1.7 releases this doesn't seem to work.

**Comment by bkaankose** [comment] 2024-06-17 13:52
> Still doesn't work for me on the current release. I get the same error with the IMAP client pool failure. Anything possible to do about that?

There was a problem with testing the IMAP connectivity in this release. I am preparing a hotfix release that will fix and help you guys to share IMAP protocol log easily for further potential problems with IMAP.

1.7.3 is expected to go live in few hours/tomorrow depending on the certification delay on Microsoft Store.

**Comment by mdfarragher** [comment] 2024-08-12 21:54
Just chiming in to confirm that this issue is still open. I tested it just now using the Store app and the 1.8.0 beta, and in both cases I was unable to connect to Proton Bridge. Setting auth to none for both IMAP and SMTP has no effect. I also enabled IMAP logging but this always produced a log file with a length of 0 bytes.

**Comment by bkaankose** [comment] 2024-08-12 22:16
> Just chiming in to confirm that this issue is still open. I tested it just now using the Store app and the 1.8.0 beta, and in both cases I was unable to connect to Proton Bridge. Setting auth to none for both IMAP and SMTP has no effect. I also enabled IMAP logging but this always produced a log file with a length of 0 bytes.

All synchronization and authentication is handled in the server companion in Beta version. So UWP has no restriction in this case. Using Proton Bridge with proper configuration must work without any blockers.

**Comment by mdfarragher** [comment] 2024-08-13 12:32
Thanks for replying! I noticed that the beta is distributed as an msixpackage so I think it has the same restrictions as the store app (it gets installed in the UWP sandbox). So I followed the advice in the link to enable loopback, and it worked! 

For anyone who had the same issues as me, an extra required step is to export the TLS certificate from Proton Bridge (you'll find the option in the advanced settings) and then install the cert.pem file in the Windows root certificate store. Instructions on how to do that are here: https://www.incredigeek.com/home/import-cert-pem-on-windows/

After I installed the TLS certificate and enabled loopback for the Wino UWP container, everything worked and I was able to access my Proton emails.

**Comment by mdfarragher** [comment] 2024-08-15 07:59
@bkaankose feel free to mark this issue as closed. With the new 1.8.0.0 version, enabling loopback and installing the TLS certificate, it should work for everyone who uses Proton now.

**Comment by Tiktack** [comment] 2024-08-15 08:04
Loopback should not be required for Wino beta anymore. Server is WPF app, which doesn't have the same restrictions like UWP.

**Comment by bkaankose** [comment] 2024-08-15 09:19
> Thanks for replying! I noticed that the beta is distributed as an msixpackage so I think it has the same restrictions as the store app (it gets installed in the UWP sandbox). So I followed the advice in the link to enable loopback, and it worked!
> 
> For anyone who had the same issues as me, an extra required step is to export the TLS certificate from Proton Bridge (you'll find the option in the advanced settings) and then install the cert.pem file in the Windows root certificate store. Instructions on how to do that are here: https://www.incredigeek.com/home/import-cert-pem-on-windows/
> 
> After I installed the TLS certificate and enabled loopback for the Wino UWP container, everything worked and I was able to access my Proton emails.

I'm glad that you figured it out. Thank you for providing the steps for others.

Even though server companion is in the same bundle, it shouldn't be blocked for loopback. UWP sandboxing should only apply for the client, not the server. I will check if something is wrong with the capabilities. 

Personally never used Proton Mail. I may run some tests to make this work all fine.

**Comment by Benjin** [comment] 2024-08-16 05:46
@mdfarragher 
> After I installed the TLS certificate and enabled loopback for the Wino UWP container, everything worked and I was able to access my Proton emails.

I don't recall having to enable loopback when I was testing this, so maybe that step isn't actually necessary as @Tiktack and @bkaankose have said.

**Comment by Benjin** [comment] 2024-08-16 05:47
@bkaankose Perhaps it'd be a good idea to embed some instructions about exporting the TLS cert that get displayed if Wino is getting configured to point to 127.0.0.1?  Otherwise, it's not a particularly discoverable solution.

**Comment by bkaankose** [comment] 2024-10-01 11:45
With latest updates (including 1.9.30) enabling loopback is not needed as far as I remember for Proton Bridge. It should just work out of the box. Settings that proton bridge client proposed always worked for me.

**Comment by huouer** [comment] 2024-10-01 21:56
I got it. I successfully added my Proton Mail by using STARTTLS and Auto. I had a folder name with "/" that prevented Wino from listing all my folders

**Comment by bkaankose** [comment] 2024-12-28 08:46
Closing this long-term issue. Proton bridge should work with Wino already.

**Closed by bkaankose** 2024-12-28 08:46 UTC
Labels: fixed
