### ISSUE TITLE
[Bug] Center of Title Bar Not Draggable on First Launch

### ISSUE THREAD

**Issue by EzraWard** [bkaankose/Wino-Mail#146] opened 2024-04-12 20:59 UTC
**Describe the bug**
When Wino is first installed and no accounts are set up, the center of the title bar does not allow dragging the window. It also does not allow double click to maximize/minimize.

**Expected behavior**
The entire title bar should be draggable and allow for double click maximize and minimize.

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/52414057/d11c8bae-b1c9-45e8-9ba8-aa6b7971164c)

**Comment by bkaankose** [comment] 2024-04-12 22:47
Duplicate of #116

**Closed by bkaankose** 2024-04-12 22:47 UTC
Labels: bug
