### ISSUE TITLE
[Proposal] Unified Inbox

### ISSUE THREAD

**Issue by claytonschase** [bkaankose/Wino-Mail#119] opened 2024-02-23 22:02 UTC
A unified inbox would be a great option to have.

**Comment by bkaankose** [comment] 2024-02-23 22:58
Development is done. Open sourced version will have it, but it'll come a little later to the Store version.

Duplicate of #60

**Closed by bkaankose** 2024-02-23 22:58 UTC
Labels: enhancement

**Comment by claytonschase** [comment] 2024-02-23 23:21
Amazing thank you so much
