### ISSUE TITLE
[Bug] no way to make wino mail default in windows 11,

### ISSUE THREAD

**Issue by sylviae15** [bkaankose/Wino-Mail#190] opened 2024-05-16 06:39 UTC
**Describe the bug     can read emails but "new Mail" or reply causes crash. microsoft help desk suggested contact developer**

**Expected behavior* *      Wino Mail does not appear in the options for default .eml or mailto

**Screenshots**

**Additional context**     trying to do any things  like reply or new mail causes wino mail to crash

**Comment by bkaankose** [comment] 2024-05-21 15:57
It is fixed in the current beta release. New version is expected to hit Microsoft Store this week.

**Comment by sylviae15** [comment] 2024-05-22 01:05
Thank you so much for letting me know. I spent a long time using quick assist with a Microsoft guy and he couldn't make it work either. I do love the program and will install the new version or update as I left it on both PC's. Thanks again kind regards Sylvia On 22 May 2024 1:27 am, Burak Kaan Köse ***@***.***> wrote:
It is fixed in the current beta release. New version is expected to hit Microsoft Store this week.

**Comment by bkaankose** [comment] 2024-06-14 17:11
Version 1.7.2 is released to Microsoft Store today. You can now set Wino Mail as your default mail application. It will support mailto protocol and .EML files to view.

Closing the issue.

**Closed by bkaankose** 2024-06-14 17:11 UTC
Labels: bug, fixed

**Comment by sylviae15** [comment] 2024-06-16 03:23
hi Burak,

have updated both my pc's with Wino Mail on them.

it certainly works better and can now be made default.

it no longer crashes when i turn off conversation threading, however there is one slight bug left.

i used to right click on my deleted folder and choose to empty the entire folder.

this does not work in Wino.

i click on the pop up asking if i want to delete all the emails but nothing happens.

i have to select " all" at the top and then click delete. not a big problem but i'm sure you would want to know.

kind regards

Sylvia Martin

**Comment by bkaankose** [comment] 2024-06-16 12:00
@sylviae15 'empty folder' and 'mark as read' for folders doesn't work in the current version, but I will include them into the hotfix version in the upcoming days.

Duplicate of #157 

Let's track the progress there.
