### ISSUE TITLE
Threads do not work

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#15] opened 2023-03-29 08:19 UTC
The app seems to lack e-mails grouped by threads. When I have notifications on for a GitHub repository for example and there are lot of comments there, I get all the notifications separated, which is very annoying

**Comment by bkaankose** [comment] 2023-03-29 16:44
Threads are created based on the following properties for each provider:

[Gmail](https://developers.google.com/gmail/api/reference/rest/v1/users.messages) - **threadId**
[Outlook](https://learn.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0) - **conversationId**

Can you confirm that same mails are displayed as threads in Mail for Windows?

**Comment by MarcAnt01** [comment] 2023-03-29 16:50
Yes, the same mails are displayed as threads on Mail for Windows

**Comment by MarcAnt01** [comment] 2023-03-30 12:51
There's certainly a buggy "threads" implementation. As you can see from the timestamps, GH mails are shown below despite being more recent, the reason is probably that they're part of threads whose first message is older
![image](https://user-images.githubusercontent.com/43090263/228841402-0eae7daf-c1c6-4a53-becc-4f474f7373ff.png)

**Comment by bkaankose** [comment] 2023-03-30 12:58
There was a bug that prevents individual mails or threads to be placed in correct group header due to datetime handling, but I don't think that's the issue. That was affecting all items, so it shouldn't cause this bug.

Ideally last item received in the thread should bump the order, but clearly its not working as intended. Thank you, I will check on this :)

**Comment by bkaankose** [comment] 2023-03-30 14:25
The issue was in shared synchronizer library, so it affects Outlook items as well for anybody interested. I was able to reproduce the issue and it'll be fixed in preview 1.3. Thanks for reporting @MarcAnt01 !

**Closed** 2023-06-26 10:31 UTC
Labels: bug, fixed
