### ISSUE TITLE
Focused tab titles have inverted colors

### ISSUE THREAD

**Issue by SOI7** [bkaankose/Wino-Mail#14] opened 2023-03-28 20:20 UTC
As you can see, the active tab titles have inverted colors and are almost impossible to read:
![image](https://user-images.githubusercontent.com/50930970/228357458-6d08ba7e-4a20-446b-91f7-87c2a29fb61e.png)

![image](https://user-images.githubusercontent.com/50930970/228357472-622b76e3-6ec9-4c62-bc4b-2f9d91ceddb7.png)

![image](https://user-images.githubusercontent.com/50930970/228357482-3965313e-32e9-44e2-86e7-4f2cf7cdef1a.png)

![Immagine 2023-03-28 221813](https://user-images.githubusercontent.com/50930970/228357505-bce2e349-a2f7-45f5-9852-c2ecf80b8f66.jpg)

**Comment by bkaankose** [comment] 2023-03-28 21:02
Can you please share your Windows version (10/11), your windows theme (light/dark) and the theme you set in Wino for me to reproduce it?

**Comment by SOI7** [comment] 2023-03-28 21:05
Windows 10 22H2, build 19045.2788. The issue happens in any Windows theme and Wino theme

**Comment by bkaankose** [comment] 2023-09-11 00:34
The issue was caused by Windows and Wino having different themes on Light mode. Not sure the exact reason was but theming in Wino has been reworked in **v1.6.2**. 

This should be fixed now. Thank you for the report @SOI7. Closing the issue. Please let me know if you encounter this issue still in v1.6.2

**Closed by bkaankose** 2023-09-11 00:34 UTC
Labels: UI
