### ISSUE TITLE
[Bug] @163.com email does not synchronize correctly v1.7.1

### ISSUE THREAD

**Issue by MilkTeaCat52** [bkaankose/Wino-Mail#200] opened 2024-05-25 11:49 UTC
**Describe the bug**
After the @163.com email is added for the first time via IMAP, synchronization completes successfully. Subsequently, synchronization fails on every attempt. The error message is: The IMAP server replied to the 'SELECT' command with a 'NO' response: SELECT Unsafe Login. Please contact kefu@188.com for help

Emails can be sent as normal.

**Expected behavior**
Synchronization of emails from the NetEase IMAP server.

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/91018175/83457d0c-0c35-42a6-a076-4788f9835daa)

**Additional context**
From another GitHub repo, the reason seems to be: "The IMAP server at imap.163.com implemented the IMAP ID extension. To successfully authenticate, the IMAP client must send client ID."
https://github.com/OfflineIMAP/offlineimap/issues/696

**Comment by bkaankose** [comment] 2024-06-18 08:50
ID extension was supported for Wino since 1.7.1, but identification is done **pre**-authentication. Looks like some servers require this before authentication and some after.

This is fixed by trying identification pre-post auth in the code, but the version is not released yet. 1.7.4 will have this fix included.

**Comment by chenseanxy** [comment] 2024-06-18 20:38
This might not be the post-auth ID thing. 126/163 supports ID pre-auth.

IMO this is more likely than not some sort of acccount ban. On the testing account I gave to @bkaankose it's still working, but not on my personal account.

More likely than not it's based on the specific app-password you use to login to IMAP, if that client gets logged with too much traffic they'll ban the specific app-password used on that account. Recreating a new password solves this issue for a while, until that gets banned again.
 
I'll ask the customer support for more help on the issue, to see if there's really any sort of ban, and if we can do anything about it.

**Comment by chenseanxy** [comment] 2024-09-30 17:18
I think I finally found the root cause to this issue, especially after the recent update which made background sync more reliable and easier to track down these issues

- Netease kicks you off the connection if idling for a while (>12h - 24h in my experience, can't reproduce this 100% of the time but it works enough of the time)
- Wino tries to reconnect, but doesn't send ID commands on reconnection
- Netease complains
- Things are fixed if you relanuch the server, therefore establishing brand new connections instead of reusing old ones

Quick writeup:

https://github.com/bkaankose/Wino-Mail/blob/a8b19e73fe32dc67d75ff67c1e9743eb30874f4b/Wino.Core/Integration/ImapClientPool.cs#L144-L160

`isCreatedNew` is always set to false, if the connection already exists (but is dead)

https://github.com/bkaankose/Wino-Mail/blob/a8b19e73fe32dc67d75ff67c1e9743eb30874f4b/Wino.Core/Integration/ImapClientPool.cs#L72-L105

Therefore `EnsureConnectivityAsync` skips the ID steps for this connection, despite it only reconnected during `EnsureConnectedAsync`

Already implemented a fix, testing this overnight see if I can reproduce this

**Closed** 2024-11-03 14:47 UTC
Labels: bug, synchronization, fixed
