### ISSUE TITLE
[Bug] No system folder (Sent, Deleted, Junk, etc...)

### ISSUE THREAD

**Issue by mrleblanc101** [bkaankose/Wino-Mail#318] opened 2024-08-17 03:38 UTC
**Describe the bug**
Sidebar only has INBOX (Why is it all caps 🤔)
I tried deleting a message, i got an error message and it asked me to configure system folder.
I did and nothing changed, i see the system folder, but they are in the more submenu and they don't have an icons.

**Expected behavior**
Once the folder are configured, the folder should be moved in the main sidebar and have the proper system icon (like in the settings).

**Screenshots**
![Capture d’écran (1)](https://github.com/user-attachments/assets/c901a7c1-26f1-4761-b3f2-945d6044d2fa)
![Capture d’écran (2)](https://github.com/user-attachments/assets/12671c8d-c330-4a1d-88d4-46fffc61a7b3)
![Capture d’écran (3)](https://github.com/user-attachments/assets/e394f0a1-de14-4265-9393-cf25d62c6e37)
![Capture d’écran (4)](https://github.com/user-attachments/assets/ac434928-6ac0-4aaf-bbdc-e57e706992c9)

**Additional context**

**Comment by mrleblanc101** [comment] 2024-08-17 03:40
Also, I notice my subfolder are not nested properly.
Toiture, Dégat d'eau, Assurance, Achat, Copropriété and Hydro should be nested inside "Condo"

**Comment by mrleblanc101** [comment] 2024-08-17 03:42
I tried manually pinning a folder in the sidebar and everything finally updated.
![Capture d’écran (5)](https://github.com/user-attachments/assets/c37590b4-4483-4e15-aab3-b5f07365378b)

**Comment by bkaankose** [comment] 2024-08-17 16:09
Looks like the app does not rebuild the folder tree on side bar menu when the configuration is changed. By default, all special folders are pinned. I will take care of it.

For the sub-folder issue I will run some tests. For me it was working fine but maybe iCloud does something different than what I covered.

**Comment by mrleblanc101** [comment] 2024-08-17 16:12
It also fixed itself at the same time as you can see in the screenshot on the second comment.

**Comment by bkaankose** [comment] 2024-09-10 07:37
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.

**Closed by bkaankose** 2024-09-10 07:37 UTC
Labels: bug, fixed, confirmed
