### ISSUE TITLE
deleting mails are too slow

### ISSUE THREAD

**Issue by Meonthb** [bkaankose/Wino-Mail#104] opened 2024-01-20 15:01 UTC
It will take up to 10 seconds or more to delete a mail. It is weird since when I use other mail client, it is instant to delete a mail.

**Comment by bkaankose** [comment] 2024-01-20 16:44
It may take that long only if you do any actions during synchronization. After the initial synchronization it should not take that long.

What happens is all your actions (like delete, mark as, move etc.) are queued **at the end of** synchronization queue. Therefore those tasks are performed when the sync is finished.

- Do you experience this behavior in every operation you do? 
- What is your mail provider? 
- Do you have good or bad network connectivitiy?

**Comment by Meonthb** [comment] 2024-01-21 05:20
Thank you, yes, finally I found the deleting lag will only appear when sync have not yet finished. But I also found the synchronization have some problems. Even if I open Wino Mail for a long time, some mails I have not opened will not been automatically synced.

thus the lag will definitely appear when I delete a mail I haven't opened.

**Comment by bkaankose** [comment] 2024-03-21 10:40
This is due to queue logic Wino has internally. Everything you do is queued and executed one by one or as batches. During synchronization this queue is on hold and only UI changes are reflected.

I have changed this logic a bit in the new version to include executing changes during sync even though it doesn't guarantee that the action is executed during sync.

Closing this issue for now since it's working as designed in the current version.

**Closed by bkaankose** 2024-03-21 10:40 UTC
