### ISSUE TITLE
[Proposal] Integration with Windows clipboard for image insertion

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#321] opened 2024-08-18 16:53 UTC
To reproduce: in Windows, the snipping tool can be invoked by Windows key + Shift + S. A screenshot or partial screenshot can then be captured to the clipboard. In Windows Mail, this clipboard image can be inserted to a draft email by selecting within the body of the email and then pasting (eg Ctrl + V).

In Wino Mail, attempting to paste from the clipboard results in a broken image icon. A current workaround is to paste the clipboard contents into an image editor (eg MS Paint), save to an image file, then drag that file into Wino Mail.

How the insertion is done in Windows Mail is probably not straightforward. It is likely that the raw image in the clipboard is saved as a png before it is inserted into the email.

**Comment by bkaankose** [comment] 2024-08-18 16:56
Current pasting bug is caused by WebView2 not handling clipboard properly for UWP. It's a limiation and known bug from MS side.

@Tiktack tested the same functionality with WinUI version of Wino and it's working there. We have plans to release WinAppSDK version of Wino later on, so this bug will be automatically fixed.

We did not want to apply a temporary fix to overcome this issue specifically.

**Comment by Tiktack** [comment] 2024-08-18 19:47
Closing as duplicate of #309

**Closed by Tiktack** 2024-08-18 19:47 UTC
Labels: enhancement
