### ISSUE TITLE
[Bug] Unable to delete emails from Gmail Sent folder

### ISSUE THREAD

**Issue by horseshoe107** [bkaankose/Wino-Mail#339] opened 2024-08-29 17:01 UTC
I found this bug on v1.8.5. It does not affect Outlook accounts, just Gmail. I first noticed this bug for emails in the Sent folder, but I think it also occurs for the "Starred" and "Important" folders. 

To reproduce bug 1:
1. Send an email from the Gmail account. It should turn up in the "Sent" folder.
2. Delete the email from Wino Mail client. The UI will appear to delete it.
3. Navigate away and return to confirm that the email has reappeared. On the Gmail server side it also confirms the email was never deleted.

To reproduce bug 2:
4. Following on from steps 1-3, delete the email from the Gmail server side. The email is moved to the "Bin".
5. Sync Wino Mail. The email is still in Wino's Sent folder.
6. Removing the Gmail account from Wino Mail and readding also results in the email still being in the Sent Folder.

As a workaround, I found that permanently deleting the email on the Gmail server side (i.e., removing it from the Bin as well) finally removes the email from Wino Mail.

If the email is deleted by Windows Mail, it moves to the Bin. Strangely, it also correctly recognised as deleted by Wino Mail. This implies that the deletion performed by Windows Mail is different from what the Gmail server does.

Hypothesis: there is a hidden "sent" property attached to the email, and when Windows Mail deletes it, it removes the sent property as well as moving it to the Bin. Gmail only moves it to the Bin. Wino Mail categorises all emails with this "sent" property into the Sent folder at a higher priority than the Bin.

**Comment by Tiktack** [comment] 2024-08-29 19:26
Reproducible only in Sent folder. Important and Starred looks fine for me.

**Comment by bkaankose** [comment] 2024-08-29 22:05
Fix has been pushed for this one. Since Outlook connects through IMAP, it works fine, but Gmail API does not allow deleting 'Sent' label from the mails. Only in Gmail web ui it's allowed.

I put some more information on the PR #341

**Comment by bkaankose** [comment] 2024-09-10 07:36
v1.9.0 that addressed this issue is released to the Store. Please re-test and re-open if you can still reproduce it.

Closing as fixed.

**Closed by bkaankose** 2024-09-10 07:36 UTC
Labels: bug, fixed
