### ISSUE TITLE
Discord link in "About" is broken 

### ISSUE THREAD

**Issue by 14142000** [bkaankose/Wino-Mail#25] opened 2023-06-30 19:13 UTC
![image](https://github.com/bkaankose/Wino-Mail/assets/3375830/7bc03d0a-1ddb-4fd0-9fe8-2984639350c1)
that link leads me to 
![image](https://github.com/bkaankose/Wino-Mail/assets/3375830/0a7aed86-49aa-4ec2-aaf6-4c6ccc8e8c2e)

**Comment by bkaankose** [comment] 2023-07-03 11:04
Unfortunately, I am not able to reproduce the experience you are having. Link opens up fine for me. **wino-mail** channel exists in Windows Apps Hub server. You can go to the server with this link https://discord.gg/N7gWjTwr

Is it possible that you have some permissions issues with this server?

**Comment by MadafakinRio** [comment] 2023-07-03 17:14
If you are not in that server then the link doesn't work. You should probably link to the server itself.

**Comment by Eziscar** [comment] 2023-07-06 08:14
You gave the link to the channel. But it wont work unless you are in the server. So you should link the server there rather than the channel link.

**Comment by bkaankose** [comment] 2023-09-11 00:30
I see the issue and fixed in **v1.6.2**.

Unfortunately Discord doesn't support channel links, even though you can create one for specific channel. Link generated will navigate users to the server instead. To deal with this I put a message when Discord option is clicked in About page.

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/723af1f3-8f07-482c-a875-d285c0f6d2e4)

After this message users are navigated to [this link](https://discord.com/invite/windows-apps-hub-714581497222398064) in. Tried with an account that is not joined to the server and it looks fine so far.

Closing the issue for now.

**Closed by bkaankose** 2023-09-11 00:30 UTC
