### ISSUE TITLE
Sending mails with IMAP doesn't work

### ISSUE THREAD

**Issue by Bingo90** [bkaankose/Wino-Mail#51] opened 2023-11-19 21:36 UTC
I tried sending a mail, but it just disappeared from the Drafts folder. When switching to another folder and then back to Drafts, the mail draft returns.

**Comment by bkaankose** [comment] 2023-11-19 21:41
UI interactions are performed immediately after the user action is taken, but local database is only affected when the actual network operation completed. Meaning that, when you send a draft mail Wino will remove it from the Drafts folder on the UI (not from the database), because that item should now potentially belong to Sent folder, but the actual item will be moved to Sent folder only if synchronizer was able to send the mail without an issue.

What you experienced is an expected behavior in Wino. Network operations don't take much time for most of the mail operations (like if you are not sending a mail with 0 mb attachment with low network connection), therefore I find this approach better in terms of feeling overall.

**Comment by Bingo90** [comment] 2023-11-19 21:52
Well, I've waited for a while now, but it still didn't send. It's just a simple test mail with the text "Test", so it shouldn't take long

**Comment by bkaankose** [comment] 2023-11-21 21:35
Looks like you had some issues with the request to the server then. I'm not exactly sure what it is, but I included bunch of fixes around sending mails and general synchronization mechanism for the next release. I hope one of those fixes will address the issue you had.

Which account type you used for this functionality?

**Comment by bkaankose** [comment] 2023-12-06 18:01
@Bingo90 Could you please try again with version 1.6.7? I believe this is fixed in that version.

**Comment by Bingo90** [comment] 2023-12-06 18:19
It does work now when using port 465!
Interestingly, when using port 587 as recommended by my ISP, I'm getting this error message ^^
![grafik](https://github.com/bkaankose/Wino-Mail/assets/28258958/8cbcff57-bdab-4e64-b1d5-1ac6985405ee)

**Comment by bkaankose** [comment] 2023-12-06 19:59
> It does work now when using port 465! Interestingly, when using port 587 as recommended by my ISP, I'm getting this error message ^^ ![grafik](https://private-user-images.githubusercontent.com/28258958/288508170-8cbcff57-bdab-4e64-b1d5-1ac6985405ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTE5NDksIm5iZiI6MTcwMTg5MTY0OSwicGF0aCI6Ii8yODI1ODk1OC8yODg1MDgxNzAtOGNiY2ZmNTctYmRhYi00ZTY0LWIxZDUtMWFjNjk4NTQwNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDE5NDA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjI4ZmVlYjMwYWUzZDMwYTMzMGZhZjQzOThlMTBjYmQyYzVlMWNmMWE1NjlhMGI4MTkzNzc1NmMzYzMxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgzkOPZaVkdKTCNzIcT0SKcTX8A8xvfCvpPSZy2z8Dc)

I'm glad you were able to fix the issue :) Can I close this issue?

**Comment by Bingo90** [comment] 2023-12-06 20:03
Oh right, almost forgot!

**Closed** 2023-12-06 20:02 UTC
