### ISSUE TITLE
[Bug] On reply - old message text not included

### ISSUE THREAD

**Issue by arabesso** [bkaankose/Wino-Mail#253] opened 2024-06-26 11:07 UTC
**Describe the bug**
When I press "reply", no previous message text in new message.

**Expected behavior**
When I press "reply" button - current text of email inserted into end of email.

**Comment by Tiktack** [comment] 2024-06-26 11:11
I believe duplicate of #227

**Comment by bkaankose** [comment] 2024-06-26 11:20
Closing as duplicate. We are tracking the issue on #227

**Closed by bkaankose** 2024-06-26 11:20 UTC
Labels: bug
