### ISSUE TITLE
Unified mailbox

### ISSUE THREAD

**Issue by Meonthb** [bkaankose/Wino-Mail#103] opened 2024-01-20 14:58 UTC
Could you add a unified mailbox, that collect inbox, sent items etc. of all accounts to one place? This is a common feature for other mail client, it would great if Wino Mail also have this feature.

**Comment by bkaankose** [comment] 2024-01-20 16:06
Unified inbox feature will be released in February.

**Comment by bkaankose** [comment] 2024-01-20 17:06
Closing this one as duplicate of #60

**Closed by bkaankose** 2024-01-20 17:06 UTC
Labels: fixed
