### ISSUE TITLE
[Bug]Reply to an email doesn't show previous content or anything at all

### ISSUE THREAD

**Issue by zkkzkk32312** [bkaankose/Wino-Mail#271] opened 2024-07-04 19:17 UTC
**Describe the bug**
When replying an email, the content of the previous email is not showing up, you start with no content in the reply.

**Expected behavior**
Shows the previous email chain's content.

**Screenshots**
N/A

**Additional context**
version 1.7.4.0

**Comment by bkaankose** [comment] 2024-07-10 08:24
v1.7.6 is released today. This should be fixed. Please give it a try and close the issue if you think it's fixed.

**Comment by bkaankose** [comment] 2024-07-10 08:27
Actually, closing the issue since it's a duplicate of #227. Please track the effort there.

**Closed by bkaankose** 2024-07-10 08:27 UTC
Labels: bug, fixed
